### ISSUE TITLE
Classe Conta

### ISSUE THREAD

**Issue by Isaius** [Isaius/aula_git#2]

**Comment by alvaro-ian** [comment]
Fazendo a review:

Observação na linha 12 arquivo Conta.java no [commit aqui descrito](https://github.com/Isaius/aula_git/commit/c3eff87bf84199a7e55488f26f309a36ddcfba78)

**Comment by Isaius** [comment]
Alterar linhas 9 para mudar o nome do atributo de codigo para numero. 
Linha 18 alterar metodo de getCodigo para getNumero
