### ISSUE TITLE
Classe Deposito

### ISSUE THREAD

**Issue by Isaius** [Isaius/aula_git#6]

**Comment by caiobjedi** [comment]
Álvaro, caso der erro de inserção de valores inválidos, tua classe não esta tratando isso

**Comment by alvaro-ian** [comment]
Isaias disse que é desnecessário pra essa aplicação de exemplo.

**Comment by caiobjedi** [comment]
na linha de operacao vc esta fazendo uma subtracao nao uma soma como se espera de um deposito

**Comment by alvaro-ian** [comment]
Cé louco cachoeira, é memo ó
