### ISSUE TITLE
Abrir Conta

### ISSUE THREAD

**Issue by Isaius** [Isaius/aula_git#8]

**Comment by Isaius** [comment]
Tem alguns erros.
Linha 7: o metodo construtor ta com o nome diferente da classe.
Além disso ta criando um banco pra por 1 cliente e 1 conta. Não faz sentido isso. Se for seguir assim teriamos que ter uma lista de bancos onde cada lista teria um cliente, já que pra criar uma nova conta teria que usar o método AbreConta e ele cria 1 banco, 1 cliente, 1 conta, e junta tudo.
O mais correto seria criar apenas um método na classe main para fazer isso. Adicionar um atributo banco nela que seria o principal.

**Comment by Isaius** [comment]
Move essa funcionalidade para a classe Menu.java, transformando em um método private.
Adiciona o banco como um atributo da classe Menu também, ai não vai precisar passar o banco como parâmetro.
O metodo construtor de conta recebe como parâmetro o numero da conta. Não tem o metodo setNumero nem setSaldo, é duas linhas a mais de codigo. O saldo por padrão é zero.

**Comment by caiobjedi** [comment]
vou manter a dessa maneira porque fica mais organizado. a classe menu vou usar apenas para chamar os métodos das outras classes. assim fica simples de manipular as chamadas

**Comment by caiobjedi** [comment]
fora isso ela ta funcionaria da maneira que está?

**Comment by Isaius** [comment]
Funciona. Dá pra usar
